# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [ford, vice]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username vodoo.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username kelliculpepper17 
issuehunt: # Replace with a single IssueHunt username hunterz.io
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://soforeverloved.com','https://crimewatchdaily.com','https://Coronavirus.org','https://Wikimedia.org','https://dial.com','https://Whitehouse.gov']
